apiVersion: v1
kind: Service
metadata:
  name: wrong-interface-container-args-service
spec:
  selector:
    app: kube-wrong-interface-container-args
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8765
  type: NodePort
