apiVersion: v1
kind: Pod
metadata:
  name: kube-wrong-interface-container-args
  labels:
    app: kube-wrong-interface-container-args
spec:
  containers:
  - name: kube-wrong-interface-container-args
    image: kube-wrong-interface-container-args-app:latest
    imagePullPolicy: Never
    command:
    - python3
    - server.py
    args:
    - --host
    - 127.0.0.1
    ports:
    - containerPort: 8765
