apiVersion: v1
kind: Pod
metadata:
  name: readiness-slow-start-app
  labels:
    app: readiness-slow-start-app
spec:
  containers:
  - name: app
    image: kube-readiness-slow-start-app:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 8080
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 1
      periodSeconds: 3
      timeoutSeconds: 1
      failureThreshold: 1
