apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-wrong-port
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-wrong-port
  template:
    metadata:
      labels:
        app: kube-wrong-port
    spec:
      containers:
      - name: kube-wrong-port
        image: marioutsa/kube-wrong-port-app
        ports:
        - containerPort: 8000
