apiVersion: v1
kind: Secret
metadata:
  name: selector-env-secret
type: Opaque
stringData:
  wrong_message: hello-from-secret
---
apiVersion: v1
kind: Pod
metadata:
  name: selector-env-secret-app
  labels:
    app: selector-env-secret-app
spec:
  containers:
  - name: app
    image: kube-selector-env-secret-app:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 8080
    env:
    - name: APP_MESSAGE
      valueFrom:
        secretKeyRef:
          name: selector-env-secret
          key: message
