apiVersion: v1
kind: Pod
metadata:
  name: kube-liveness-wrong-path
spec:
  containers:
  - name: kube-liveness-wrong-path
    image: kube-liveness-wrong-path-app:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 8765
    livenessProbe:
      httpGet:
        path: /livez
        port: 8765
      initialDelaySeconds: 2
      periodSeconds: 3
      failureThreshold: 1
