apiVersion: v1
kind: Pod
metadata:
  name: kube-wrong-port-9090
spec:
  containers:
  - name: kube-wrong-port-9090
    image: kube-wrong-port-9090-app
    imagePullPolicy: Never
    ports:
    - containerPort: 8080
