apiVersion: v1
kind: Pod
metadata:
  name: kube-missing-dependency-requirements
spec:
  containers:
  - name: kube-missing-dependency-requirements
    image: kube-missing-dependency-requirements-app:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 8765
