apiVersion: v1
kind: Pod
metadata:
  name: kube-wrong-interface-env-host
  labels:
    app: kube-wrong-interface-env-host
spec:
  containers:
  - name: kube-wrong-interface-env-host
    image: kube-wrong-interface-env-host-app:latest
    imagePullPolicy: Never
    env:
    - name: APP_HOST
      value: "127.0.0.1"
    ports:
    - containerPort: 8765
