apiVersion: v1
kind: Pod
metadata:
  name: kube-wrong-interface-bind-address
  labels:
    app: kube-wrong-interface-bind-address
spec:
  containers:
  - name: kube-wrong-interface-bind-address
    image: kube-wrong-interface-bind-address-app:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 8765
