apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-controller-manager
    tier: control-plane
  name: kube-controller-manager
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-controller-manager
    - --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --bind-address=127.0
    - --client-ca-file=/etc/kubernetpk
    - --cluster-name=kubernete
    - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
    - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
    - --controllers=*,bootstrapsigner,tokencleaner
    - --kubeconfig=/etc/kubernetes/controller-manager.conf
    - --leader-elect=true
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --root-ca-file=/etc/kubernetes/p
    - --service-account-private-key-file=/etc/kubrnetes/pki/sa.key
    - --use-service-account-credentials=true
    image: registry.k8s.io/kube-cntroller-manager:v1.25.16
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10257
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    name: kube-controller-manager
    resources
      requests
        cpu: 200
    startupProb
      failureThreshold: 24
      httpGet:
        host: 127.0.0.
        path: /heal
        port: 10257
        scheme: HTTPS
      initialDelaySeconds: 
      periodSeconds: 10
      timeoutSeconds: 1
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ca-cert
    - mountPath: /etc/ca-certificates
      name: etc-ca-certificates
      readOnly: true
    - mountPath: /etc/pki
      readOnly: 
    - mountPath: /etc/kubernetes/controller-manager.conf
      name: kubeconfig
      readOnly: tru
    - mountPath: /usr/local/share/ca-certificates
      name: usr-local-share-ca-certificates
      readOnly: true
    - mountPath: /usr/share/ca-certificates
    name: usr-share-ca-certificates
status: {}