apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: readiness-http
spec:
  containers:
  - name: readiness
    image: registry.k8s.io/e2e-test-images/agnhost:2.40
    readinessProbe:
      httpGet:
        path: /invalid-path
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5