apiVersion: v1
kind: Pod
metadata:
  name: kube-port-mismatch
  labels:
    app: kube-port-mismatch
spec:
  containers:
  - name: kube-port-mismatch
    image: marioutsa/kube-port-mismatch-app
    ports:
      - containerPort: 8000
