apiVersion: v1
kind: Pod
metadata:
  name: kube-port-mismatch
  labels:
    app: kube-port-mismatch  # <-- Match this with the service selector
spec:
  containers:
  - name: kube-port-mismatch
    image: marioutsa/kube-port-mismatch-app
    ports:
      - containerPort: 8765  # <-- Ensure this matches the application port
