apiVersion: v1
kind: Pod
metadata:
  name: kube-liveness
spec:
  containers:
  - name: kube-liveness
    image: marioutsa/kube-liveness-app
    ports:
            - containerPort: 8765
    livenessProbe:
      httpGet:
        path: /health
        port: 8765
      initialDelaySeconds: 30
      periodSeconds: 10
