apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-liveness-deployment
spec:
  selector:
    matchLabels:
      app: kube-liveness
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-liveness
    spec:
      containers:
      - name: kube-liveness
        image: marioutsa/kube-liveness-app
        livenessProbe:
          httpGet:
            path: /health
            port: 8765
          initialDelaySeconds: 30
          periodSeconds: 10
