apiVersion: v1
kind: Pod
metadata:
  name: kube-selector-missing-label
  labels:
    tier: frontend
spec:
  containers:
  - name: kube-selector-missing-label
    image: kube-selector-missing-label-app:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 8765
