apiVersion: v1
kind: Pod
metadata:
  name: kube-missing-dependency
spec:
  containers:
  - name: kube-missing-dependency
    image: marioutsa/kube-missing-dependency-app
    ports:
        - containerPort: 8765
    command: ["python", "server.py"]
