apiVersion: v1
kind: Pod
metadata:
  name: kube-port-mismatch-named-target
  labels:
    app: kube-port-mismatch-named-target
spec:
  containers:
  - name: kube-port-mismatch-named-target
    image: kube-port-mismatch-named-target-app:latest
    imagePullPolicy: Never
    ports:
    - name: http-app
      containerPort: 8765
